"use client";

import { useState } from "react";

const STEPS = [
  ["01", "Connect your store & carriers", "Complete Bellmont's onboarding flow, sync orders, products, and customers, then connect Shopify, WooCommerce, BigCommerce, Wix, UPS, FedEx, and USPS."],
  ["02", "Set up shipping logic", "Configure your shipping schedule, service display logic, order protection, zones, and rule automations around location, weather, transit time, and risk."],
  ["03", "Go live & optimize", "Print labels, manage shipments and claims, automate box splitting, adjust rates, and give every recipient a clear delivery ETA from one live record."],
] as const;

function SetupPreview({ active }: { active: number }) {
  if (active === 1) return <div className="hv2-setup-board hv2-logic-board"><div className="hv2-board-column"><div className="hv2-board-card"><header><b>Display Logic</b><button>+ Add</button></header>{["Zone 1 (West) → Next Day Air", "Zone 2 (Mid to East) → Standard O/N", "Restrict Local LA → Lowest Rate", "All Regions → Cheapest Anytime"].map((rule) => <div className="hv2-rule" key={rule}>{rule}<span>✎　▧</span></div>)}</div><div className="hv2-board-card"><header><b>Zones</b><button>+ Add</button></header><div className="hv2-table-head">NAME <span>REGIONS</span></div>{[["Zone 1 (West)", "CA, AZ, NV, UT"], ["Zone 2 (East)", "AL, AK, AZ, AR, CA, …"], ["Local LA", "90001, 90002, 90003, …"], ["Zone 3 (South)", "TX, FL, GA, LA, MS, …"]].map(([name, region]) => <div className="hv2-zone-row" key={name}><b>{name}</b><span>{region}</span></div>)}</div></div><div className="hv2-board-column"><div className="hv2-board-card hv2-protection"><header><b>Order Protection</b><span className="hv2-toggle on" /></header><p>Customer pays 3% of order value</p><div className="hv2-protect-inner"><b>ORDER PROTECTION</b><small>Safeguard shipments against delays, damage & more.</small><strong>$4.50</strong></div><div className="hv2-chips"><span>Subscription ×</span><span>Recurring Order ×</span></div></div><div className="hv2-board-card"><header><b>Automations</b><button>+ Add</button></header>{["High Temp. Destination", "Short Transit Packaging", "Lower Confidence Coverage"].map((rule) => <div className="hv2-auto-row" key={rule}><span>⁝⁝</span><b>{rule}</b><span className="hv2-toggle on" /><span>✎　▧</span></div>)}</div></div></div>;
  if (active === 2) return <div className="hv2-setup-board hv2-dashboard-board"><div className="hv2-dashboard-head"><span><i /> <i /> <i />　Dashboard</span><span>Mar 1 – Mar 25, 2026　 <b>● Live</b></span></div><div className="hv2-dashboard-stats">{[["Total Rated Spend", "$22,058"], ["Labels Purchased", "446"], ["Cost per Package", "$49.46"], ["Avg Transit Days", "1"]].map(([label, value]) => <div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><div className="hv2-dashboard-charts"><div className="hv2-chart-card"><h4>Spend</h4><div className="hv2-bars">{[25, 58, 48, 82, 64, 53, 70].map((height, index) => <i style={{ height: `${height}%` }} key={index} />)}</div><small>Mar 2　 5　 8　 12　 16　 20　 25</small></div><div className="hv2-chart-card"><h4>Carrier Split</h4><div className="hv2-donut"><b>446<small>Total</small></b></div><p><span className="orange-dot" />81.6% UPS　<span className="blue-dot" />18.2% FedEx　<span className="gray-dot" />0% USPS</p></div></div><div className="hv2-dashboard-table"><div><b>CARRIER</b><b>SERVICE</b><b>TOTAL SPEND</b><b>LABELS</b></div>{[["UPS", "Next Day Air Saver", "$9,768", "165"], ["", "Next Day Air", "$4,345", "62"], ["", "Ground", "$2,226", "117"], ["FedEx", "Standard Overnight", "$4,863", "81"]].map((row, index) => <div key={index}><b>{row[0]}</b><span>{row[1]}</span><strong>{row[2]}</strong><span>{row[3]}</span></div>)}</div></div>;
  return <div className="hv2-setup-board hv2-onboarding-board"><img className="hv2-onboarding-art" src="/media/bellmont-onboarding-carriers.png" alt="Bellmont onboarding dashboard with Shopify, UPS, FedEx, and USPS connected" /></div>;
}

export function TrustMarquee() { return <section className="hv2-trust home-trust-logos" aria-label="Bellmont customer logos"><p className="hv2-marquee-label">Trusted by teams that move important things</p><div className="home-trust-logos__mask"><div className="home-trust-logos__track"><img src="/media/bellmont-home-logos-a.png" alt="Bellmont customer logos" /><img src="/media/bellmont-home-logos-b.png" alt="Bellmont customer logos" /><img src="/media/bellmont-home-logos-a.png" alt="" aria-hidden="true" /><img src="/media/bellmont-home-logos-b.png" alt="" aria-hidden="true" /></div></div></section>; }

export function PostFeatureSections() {
  const [active, setActive] = useState(0);
  return <>
    <section className="hv2-hiw bg-white"><div className="hv2-container hv2-hiw-pin"><div className="hv2-sec-head hv2-sec-head-compact"><span className="hv2-eyebrow"><span className="hv2-eyebrow-dot" />Set up in minutes</span><h2 className="hv2-h2">A calmer way to run freight.</h2><p className="hv2-sec-sub">Bellmont streamlines your entire logistics operation—from checkout to delivery, all in one platform.</p></div><div className="hv2-hiw-grid hv2-setup-grid"><div className="hv2-setup-steps">{STEPS.map(([number, title, body], index) => <button type="button" className={`hv2-step ${active === index ? "hv2-step-active" : ""}`} onClick={() => setActive(index)} key={number}><span className="hv2-step-tick">{number}</span><span className="hv2-step-content"><span className="hv2-step-title">{title}</span><span className="hv2-step-body">{body}</span></span></button>)}</div><SetupPreview active={active} /></div></div></section>
    <section className="hv2-network"><div className="hv2-container"><div className="hv2-sec-head"><span className="hv2-eyebrow"><span className="hv2-eyebrow-dot" />One living record</span><h2 className="hv2-h2">Every handoff, connected.</h2><p className="hv2-sec-sub">Your storefront, carriers, operations team, and recipients work from the same source of truth.</p></div><div className="hv2-network-board"><div className="hv2-network-node hv2-network-node--top">Commerce<br /><small>Orders + customers</small></div><div className="hv2-network-node hv2-network-node--left">Carriers<br /><small>Ocean · Air · Road</small></div><div className="hv2-network-node hv2-network-node--right">Operations<br /><small>Rules + exceptions</small></div><div className="hv2-network-hub"><span className="hv2-network-mark">B</span><b>Bellmont</b><small>live record</small></div><div className="hv2-network-node hv2-network-node--bottom">Recipient experience<br /><small>Tracking + support</small></div></div></div></section>
  </>;
}

export default function HomeV2Sections() { return <><TrustMarquee /><PostFeatureSections /></>; }
