"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

const features = [
  ["01", "Shipping & Courier Management", "Access Bellmont's carrier network, live rates, and delivery management in one place."],
  ["02", "Claim Management & Coverage", "File claims directly from the platform and replace the usual hassle with a streamlined workflow."],
  ["03", "Shipping Rules & Automations", "Set smart rules for any scenario and automate the shipping logic your operation needs."],
  ["04", "Auto Box Splitting Algorithm", "Automatically determine the ideal number of shipments for every order."],
];

export default function RatesPage() {
  const [submitted, setSubmitted] = useState(false);
  const [form, setForm] = useState({ from: "", to: "", length: "10", width: "10", height: "10", weight: "10" });
  function submit(event: FormEvent) { event.preventDefault(); setSubmitted(true); }
  return <main className="rates-page">
    <section className="rates-hero"><div className="rates-shell rates-hero-grid"><div><span className="rates-badge">▣　Shipping Rate Calculator</span><h1>Perishable shipping<br />rate calculator —<br /><span>Find out how much<br />you can save</span></h1><p>Bellmont's rate calculator gives shippers an instant price check on the services they need most. <b>Compare overnight, 2-day, and ground rates</b> and find the best route for your business.</p><div className="rates-metrics"><span><b>30%</b><small>Avg. Cost Savings</small></span><span><b>25%+</b><small>Conversion Lift</small></span><span><b>3–5%</b><small>Extra Revenue/Order</small></span></div><div className="rates-actions"><Link href="/book-demo" className="rates-btn rates-btn-ghost">▣　Book a Demo</Link><Link href="/tracking" className="rates-btn rates-btn-orange">Get Started　→</Link></div></div><form className="rates-calculator" onSubmit={submit}><div className="rates-calc-title"><span>▣</span><b>Bellmont+</b> Rate Calculator<small>Compare us against other major shipping platforms</small></div><div className="rates-form-grid"><label>Ship From ZIP<input required value={form.from} placeholder="e.g. 90210" onChange={(e) => setForm({ ...form, from: e.target.value })} /></label><label>Ship To ZIP *<input required value={form.to} placeholder="e.g. 33139" onChange={(e) => setForm({ ...form, to: e.target.value })} /></label></div><label className="rates-check"><input type="checkbox" /> Residential Address</label><label>Package Dimensions (Inches)<span className="rates-dimensions"><input value={form.length} onChange={(e) => setForm({ ...form, length: e.target.value })} /><input value={form.width} onChange={(e) => setForm({ ...form, width: e.target.value })} /><input value={form.height} onChange={(e) => setForm({ ...form, height: e.target.value })} /></span></label><label>Package Weight<input value={form.weight} onChange={(e) => setForm({ ...form, weight: e.target.value })} /></label><button className="rates-submit" type="submit">{submitted ? "Rates Ready — View Options" : "Check Rates"}</button>{submitted && <p className="rates-result">Your Bellmont rate comparison is ready. We found optimized service options for this route.</p>}</form></div><div className="rates-trust-strip" aria-label="Bellmont customer logos"><div className="rates-logo-track"><img src="/media/bellmont-trust-logos-a.png" alt="Bellmont customer logos" /><img src="/media/bellmont-trust-logos-b.png" alt="Bellmont customer logos" /><img src="/media/bellmont-trust-logos-a.png" alt="" aria-hidden="true" /><img src="/media/bellmont-trust-logos-b.png" alt="" aria-hidden="true" /></div></div></section>
    <section className="rates-features"><div className="rates-shell rates-section-head"><span className="rates-badge">⚒　Platform Features</span><h2>Everything you need to ship<br /><span>faster, smarter, and for less</span></h2><p>Bellmont optimizes shipping with weather-aware routing, rule automations, order protection, and savings on every shipment.</p></div><div className="rates-shell rates-feature-grid">{features.map(([number, title, copy]) => <article key={number}><span className="rates-feature-icon">{number === "01" ? "▣" : number === "02" ? "▤" : number === "03" ? "⌘" : "▦"}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="rates-guide"><div className="rates-shell rates-guide-grid"><div><span className="rates-badge">▤　Shipping Cost Guide</span><h2>How much does it cost to<br /><span>ship food overnight?</span></h2><p>Shipping food overnight can range widely, typically <b>between $45–$85 per shipment</b> depending on weight, dimensions, and distance. Costs can rise when special services are added, such as Saturday Delivery or dry ice.</p><p>For most brands, it's about optimizing the lowest-cost method across multiple services while still delivering goods cold and intact. Bellmont accounts for time in transit, weather, and deliverability risks.</p><h4>Key factors that impact overnight shipping costs</h4><ul><li>Weight & DIM weight — Oversized boxes can drive rates up significantly.</li><li>Zone distance — Shorter distances cost less for overnight delivery.</li><li>Insulation & dry ice — Adds weight and may trigger special handling fees.</li><li>Carrier surcharges — Fuel, residential, and extended-area fees stack quickly.</li></ul><div className="rates-actions"><Link href="/book-demo" className="rates-btn rates-btn-ghost">▣　Book a Demo</Link><Link href="/tracking" className="rates-btn rates-btn-orange">Get Started　→</Link></div></div><img src="/media/bellmont-cold-chain-box.png" alt="Bellmont cold-chain shipment" /></div></section>
    <section className="rates-results"><div className="rates-shell rates-section-head"><span className="rates-badge">•　A tool you can trust</span><h2>See why leading logistics teams<br /><span>trust Bellmont</span></h2><p>Real results from teams who have transformed their operations with Bellmont.</p></div><div className="rates-proof-marquee" aria-label="Bellmont customer testimonials"><div className="rates-proof-track"><img src="/media/bellmont-testimonials-a.png" alt="Bellmont customer testimonials" /><img src="/media/bellmont-testimonials-b.png" alt="Bellmont customer testimonials" /><img src="/media/bellmont-testimonials-a.png" alt="" aria-hidden="true" /><img src="/media/bellmont-testimonials-b.png" alt="" aria-hidden="true" /></div></div></section>
  </main>;
}
